### ISSUE TITLE
Promote FSA

### ISSUE THREAD

**Issue by dariocravero** [dferber90/webapp#2]
Promote the use of [Flux Standard Actions](https://github.com/acdlite/flux-standard-action) where payload is an object in [action creators](https://github.com/dferber90/webapp-starter-pack/blob/master/app/common/actionCreators/todos.js#L6).

**Comment by dferber90** [comment]
Thanks, added in https://github.com/dferber90/webapp-starter-pack/commit/2f970415472e5f94d362d0aeb136bb12184c35c7.
