### ISSUE TITLE
Adding links to relevant docs in comments

### ISSUE THREAD

**Issue by chrisvfritz** [dferber90/webapp#9]
What would you think about adding links to relevant documentation/issues from various projects to explain each part of the application? For example, folks familiar with the simpler configuration of `react-router` might initially be confused if they don't understand the more advanced configuration, why it's useful, and how to use it.

**Comment by dferber90** [comment]
Thanks for getting in touch :+1: 

I plan to write extensive documentation in case this project reaches a state that's worth it, briefly introducing each interesting dependency (webpack, react, redux, react-router) and linking to their documentation for details.

Your suggestion sounds like a great additional resource for newcomers. Right now it probably isn't worth it yet as the project is still in the experimentation phase and a lot is changing.

**Comment by chrisvfritz** [comment]
Got it. Thanks for the prompt response! I'll close this for now.
